// Generated by CoffeeScript 1.3.1
(function() {

  this.LPJ = typeof LPJ !== "undefined" && LPJ !== null ? LPJ : {};

  LPJ.Actions = {
    gauche: "gauche",
    haut: "haut",
    droit: "droit",
    bas: "bas",
    bombe: "bombe"
  };

}).call(this);
